import assert from "node:assert/strict";
import { after, afterEach, before, describe, it } from "node:test";
import request from "supertest";
import { GOOGLE_CALENDAR_READONLY_SCOPE } from "../src/connectors/googleCalendarAdapter.js";
import { prisma } from "../src/db.js";
import { createServer } from "../src/server.js";
import { resetDb, seedCompanyAndAdmin } from "./setup.js";
const app = createServer(); const originalFetch = globalThis.fetch;
const env = { id: process.env.GOOGLE_CALENDAR_OAUTH_CLIENT_ID, secret: process.env.GOOGLE_CALENDAR_OAUTH_CLIENT_SECRET, redirect: process.env.GOOGLE_CALENDAR_OAUTH_REDIRECT_URI, key: process.env.CONNECTOR_ENCRYPTION_KEY };
const urlOf = (input: string | URL | Request) => new URL(typeof input === "string" ? input : input instanceof URL ? input.toString() : input.url);

describe("Google Calendar read-only connector", () => {
  let token: string, sourceId: string, state: string;
  before(async () => { process.env.GOOGLE_CALENDAR_OAUTH_CLIENT_ID = "calendar.apps.googleusercontent.com"; process.env.GOOGLE_CALENDAR_OAUTH_CLIENT_SECRET = "secret"; process.env.GOOGLE_CALENDAR_OAUTH_REDIRECT_URI = "http://localhost:4000/connectors/google-calendar/oauth/callback"; process.env.CONNECTOR_ENCRYPTION_KEY = Buffer.alloc(32, 4).toString("base64"); await resetDb(); await seedCompanyAndAdmin(); token = (await request(app).post("/auth/login").send({ email: "admin@test.local", password: "Password123!" })).body.token; const source = await request(app).post("/connectors/sources").set("Authorization", `Bearer ${token}`).send({ connector_key: "google_calendar", display_name: "Operations calendar", configured_scopes: ["read:calendar"] }); assert.equal(source.status, 201); sourceId = source.body.id; });
  afterEach(() => { globalThis.fetch = originalFetch; });
  after(async () => { await resetDb(); await prisma.$disconnect(); const values = { GOOGLE_CALENDAR_OAUTH_CLIENT_ID: env.id, GOOGLE_CALENDAR_OAUTH_CLIENT_SECRET: env.secret, GOOGLE_CALENDAR_OAUTH_REDIRECT_URI: env.redirect, CONNECTOR_ENCRYPTION_KEY: env.key }; for (const [key, value] of Object.entries(values)) value === undefined ? delete process.env[key] : process.env[key] = value; });

  it("authorizes only calendar.readonly and stores encrypted credentials", async () => { const start = await request(app).post(`/connectors/sources/${sourceId}/oauth/start`).set("Authorization", `Bearer ${token}`).send({}); assert.equal(start.status, 200); const auth = new URL(start.body.authorizationUrl); assert.equal(auth.searchParams.get("scope"), GOOGLE_CALENDAR_READONLY_SCOPE); state = auth.searchParams.get("state")!; globalThis.fetch = async input => { assert.equal(urlOf(input).toString(), "https://oauth2.googleapis.com/token"); return Response.json({ access_token: "calendar-access", refresh_token: "calendar-refresh", expires_in: 3600, scope: GOOGLE_CALENDAR_READONLY_SCOPE }); }; const callback = await request(app).get("/connectors/google-calendar/oauth/callback").query({ state, code: "code" }); assert.equal(callback.status, 303); const stored = await prisma.connectorCredential.findUniqueOrThrow({ where: { sourceId } }); assert.equal(stored.provider, "google_calendar"); assert.ok(!JSON.stringify(stored).includes("calendar-access")); await request(app).post(`/connectors/sources/${sourceId}/enable`).set("Authorization", `Bearer ${token}`).send({ confirmed: true }).expect(200); });

  it("stages calendars and events without changing jobs or tasks", async () => { globalThis.fetch = async input => { const url = urlOf(input); if (url.pathname.endsWith("/calendarList")) { assert.equal(url.searchParams.get("showDeleted"), "true"); return Response.json({ items: [{ id: "primary@example.com", summary: "Primary", primary: true, timeZone: "Europe/London", accessRole: "owner" }], nextSyncToken: "calendar-sync-1" }); } assert.ok(url.pathname.includes("/calendars/primary%40example.com/events")); assert.equal(url.searchParams.get("singleEvents"), "false"); return Response.json({ items: [{ id: "event-1", status: "confirmed", summary: "Site visit", location: "Oxford", start: { dateTime: "2026-08-01T09:00:00Z" }, end: { dateTime: "2026-08-01T10:00:00Z" }, organizer: { email: "boss@example.com" }, attendees: [{ email: "client@example.com" }] }], nextSyncToken: "event-sync-1" }); }; const sync = await request(app).post(`/connectors/sources/${sourceId}/sync`).set("Authorization", `Bearer ${token}`).send({}); assert.equal(sync.status, 200); assert.equal(sync.body.eventsUpserted, 1); assert.equal(await prisma.job.count(), 0); assert.equal(await prisma.task.count(), 0); const event = await prisma.externalCalendarEvent.findFirstOrThrow(); assert.equal(event.summary, "Site visit"); assert.equal(event.organiserEmail, "boss@example.com"); });

  it("uses incremental tokens and archives cancelled events", async () => { globalThis.fetch = async input => { const url = urlOf(input); if (url.pathname.endsWith("/calendarList")) { assert.equal(url.searchParams.get("syncToken"), "calendar-sync-1"); return Response.json({ nextSyncToken: "calendar-sync-2" }); } assert.equal(url.searchParams.get("syncToken"), "event-sync-1"); return Response.json({ items: [{ id: "event-1", status: "cancelled" }], nextSyncToken: "event-sync-2" }); }; const sync = await request(app).post(`/connectors/sources/${sourceId}/sync`).set("Authorization", `Bearer ${token}`).send({}); assert.equal(sync.status, 200); assert.equal(sync.body.eventsDeleted, 1); assert.equal((await prisma.externalCalendarEvent.findFirstOrThrow()).isDeleted, true); });

  it("clears stale event storage and full-syncs after HTTP 410", async () => { let eventCalls = 0; globalThis.fetch = async input => { const url = urlOf(input); if (url.pathname.endsWith("/calendarList")) return Response.json({ nextSyncToken: "calendar-sync-3" }); eventCalls++; if (eventCalls === 1) { assert.equal(url.searchParams.get("syncToken"), "event-sync-2"); return new Response("{}", { status: 410 }); } assert.equal(url.searchParams.has("syncToken"), false); return Response.json({ items: [{ id: "event-2", status: "confirmed", summary: "Replacement", start: { date: "2026-08-02" }, end: { date: "2026-08-03" } }], nextSyncToken: "event-sync-3" }); }; const sync = await request(app).post(`/connectors/sources/${sourceId}/sync`).set("Authorization", `Bearer ${token}`).send({}); assert.equal(sync.status, 200); assert.equal(sync.body.eventFallbacks, 1); assert.equal(await prisma.externalCalendarEvent.count(), 1); assert.equal((await prisma.externalCalendarEvent.findFirstOrThrow()).externalEventId, "event-2"); });

  it("lists staged events and disconnects without deleting them", async () => { const list = await request(app).get(`/connectors/sources/${sourceId}/external-calendar-events`).set("Authorization", `Bearer ${token}`); assert.equal(list.status, 200); assert.equal(list.body.total, 1); const preview = await request(app).post(`/connectors/sources/${sourceId}/disconnect`).set("Authorization", `Bearer ${token}`).send({ confirmed: false }); assert.equal(preview.status, 409); globalThis.fetch = async () => new Response(null, { status: 200 }); const done = await request(app).post(`/connectors/sources/${sourceId}/disconnect`).set("Authorization", `Bearer ${token}`).send({ confirmed: true }); assert.equal(done.status, 200); assert.equal(await prisma.externalCalendarEvent.count(), 1); });
});
