import { createHash, randomBytes } from "node:crypto";
import { Prisma } from "@prisma/client";
import { z } from "zod";
import { prisma } from "../db.js";
import { assertConnectorEncryptionConfigured, ConnectorCryptoError, decryptConnectorPayload, encryptConnectorPayload } from "../connectors/connectorCrypto.js";
import { buildGoogleCalendarAuthorizationUrl, exchangeGoogleCalendarAuthorizationCode, GoogleCalendarAdapterError, listGoogleCalendarEvents, listGoogleCalendars, refreshGoogleCalendarCredential, revokeGoogleCalendarCredential, type GoogleCalendarEvent, type StoredGoogleCalendarCredential } from "../connectors/googleCalendarAdapter.js";
import { COMPLETE_GOOGLE_CALENDAR_OAUTH_ACTION, DISCONNECT_GOOGLE_CALENDAR_SOURCE_ACTION, START_GOOGLE_CALENDAR_OAUTH_ACTION, SYNC_GOOGLE_CALENDAR_ACTION, type ActionContract } from "../lib/actionContracts.js";
import { recordAudit } from "../lib/audit.js";
import type { AuthedUser } from "../middleware/auth.js";
import { fail, ok, type ServiceResult } from "./result.js";

const STATE_MS = 10 * 60 * 1000; const REFRESH_MARGIN = 60 * 1000;
const callbackSchema = z.object({ state: z.string().min(20).max(500), code: z.string().min(1).max(4096).optional(), error: z.string().min(1).max(200).optional() }).refine(v => Boolean(v.code) !== Boolean(v.error));
const disconnectSchema = z.object({ confirmed: z.boolean().optional() }).strict();
export const eventQuerySchema = z.object({ offset: z.coerce.number().int().min(0).default(0), limit: z.coerce.number().int().min(1).max(100).default(50), include_deleted: z.enum(["true", "false"]).optional() }).strict();
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const context = (companyId: string, sourceId: string) => `${companyId}:${sourceId}:google_calendar`;
function redirect(sourceId: string) { let base: URL; try { base = new URL(process.env.FRONTEND_URL?.trim() || "http://localhost:5173"); } catch { base = new URL("http://localhost:5173"); } const url = new URL("/connectors", base); url.searchParams.set("google_calendar", "connected"); url.searchParams.set("source", sourceId); return url.toString(); }
async function auditFailure(action: ActionContract, identity: { companyId: string; userId?: string; id?: string }, sourceId: string, errorMessage: string) { await recordAudit({ companyId: identity.companyId, userId: identity.userId ?? identity.id, actionName: action.actionName, inputPayload: { sourceId }, riskLevel: action.riskLevel, confirmationRequired: action.confirmationRequired, result: "error", errorMessage }); }
function providerError(error: unknown): ServiceResult<never> { if (error instanceof GoogleCalendarAdapterError) return fail(error.code === "RATE_LIMITED" ? 429 : ["PROVIDER_UNAVAILABLE", "CONNECTOR_CONFIGURATION_MISSING"].includes(error.code) ? 503 : error.code === "PROVIDER_RESPONSE_INVALID" ? 502 : 409, error.code, error.message); if (error instanceof ConnectorCryptoError) return fail(500, error.code); return fail(500, "CONNECTOR_INTERNAL_ERROR"); }

export async function startGoogleCalendarOAuth(user: AuthedUser, sourceId: string): Promise<ServiceResult<unknown>> {
  const source = await prisma.connectorSource.findFirst({ where: { id: sourceId, companyId: user.companyId, connectorKey: "google_calendar", isActive: true } });
  if (!source) return fail(404, "CONNECTOR_SOURCE_NOT_FOUND"); if (!source.configuredScopes.includes("read:calendar")) return fail(409, "CONNECTOR_SCOPE_REQUIRED");
  try { assertConnectorEncryptionConfigured(); const state = randomBytes(32).toString("base64url"); const authorizationUrl = buildGoogleCalendarAuthorizationUrl(state); const expiresAt = new Date(Date.now() + STATE_MS);
    await prisma.$transaction([prisma.connectorOAuthState.deleteMany({ where: { sourceId } }), prisma.connectorOAuthState.create({ data: { sourceId, companyId: user.companyId, userId: user.id, stateHash: hash(state), expiresAt } }), prisma.connectorSource.update({ where: { id: sourceId }, data: { isEnabled: false, connectionStatus: "authorizing", lastErrorCode: null } })]);
    await recordAudit({ companyId: user.companyId, userId: user.id, actionName: START_GOOGLE_CALENDAR_OAUTH_ACTION.actionName, inputPayload: { sourceId }, dataAfter: { sourceId, expiresAt }, riskLevel: 1, result: "success" }); return ok(200, { authorizationUrl, expiresAt });
  } catch (error) { const result = providerError(error); await auditFailure(START_GOOGLE_CALENDAR_OAUTH_ACTION, user, sourceId, result.ok ? "CONNECTOR_INTERNAL_ERROR" : result.error); return result; }
}

export async function completeGoogleCalendarOAuth(raw: unknown): Promise<ServiceResult<{ redirectUrl: string }>> {
  const parsed = callbackSchema.safeParse(raw); if (!parsed.success) return fail(400, "OAUTH_CALLBACK_INVALID");
  const state = await prisma.connectorOAuthState.findUnique({ where: { stateHash: hash(parsed.data.state) }, include: { source: { include: { credential: true } } } });
  if (!state || state.consumedAt) return fail(400, "OAUTH_STATE_INVALID");
  if (state.source.connectorKey !== "google_calendar" || !state.source.isActive) { await prisma.connectorOAuthState.update({ where: { id: state.id }, data: { consumedAt: new Date() } }); return fail(404, "CONNECTOR_SOURCE_NOT_FOUND"); }
  const user = await prisma.user.findFirst({ where: { id: state.userId, companyId: state.companyId, isActive: true }, select: { permissions: true } });
  if (!user?.permissions.includes("connectors.manage")) return fail(403, "MISSING_PERMISSION"); if (state.expiresAt <= new Date()) return fail(400, "OAUTH_STATE_EXPIRED");
  const consumed = await prisma.connectorOAuthState.updateMany({ where: { id: state.id, consumedAt: null, expiresAt: { gt: new Date() } }, data: { consumedAt: new Date() } }); if (consumed.count !== 1) return fail(400, "OAUTH_STATE_INVALID"); if (parsed.data.error) return fail(409, "OAUTH_PROVIDER_REJECTED");
  try { let oldRefresh: string | undefined; if (state.source.credential) oldRefresh = decryptConnectorPayload<StoredGoogleCalendarCredential>(state.source.credential, context(state.companyId, state.sourceId)).refreshToken;
    const value = await exchangeGoogleCalendarAuthorizationCode(parsed.data.code!, oldRefresh); const encrypted = encryptConnectorPayload(value, context(state.companyId, state.sourceId));
    await prisma.$transaction([prisma.connectorCredential.upsert({ where: { sourceId: state.sourceId }, create: { sourceId: state.sourceId, companyId: state.companyId, provider: "google_calendar", ...encrypted }, update: { provider: "google_calendar", ...encrypted } }), prisma.connectorSource.update({ where: { id: state.sourceId }, data: { connectionStatus: "configured", isEnabled: false, lastErrorCode: null, syncCursor: null, syncPageToken: null, lastFullSyncAt: null } })]);
    await recordAudit({ companyId: state.companyId, userId: state.userId, actionName: COMPLETE_GOOGLE_CALENDAR_OAUTH_ACTION.actionName, inputPayload: { sourceId: state.sourceId }, dataAfter: { provider: "google_calendar", scopeVerified: true, encrypted: true }, riskLevel: 2, result: "success" }); return ok(200, { redirectUrl: redirect(state.sourceId) });
  } catch (error) { return providerError(error); }
}

type Source = Prisma.ConnectorSourceGetPayload<{ include: { credential: true } }>;
async function usable(source: Source) { const c = context(source.companyId, source.id); let value = decryptConnectorPayload<StoredGoogleCalendarCredential>(source.credential!, c); if (!Number.isFinite(Date.parse(value.expiresAt)) || Date.parse(value.expiresAt) <= Date.now() + REFRESH_MARGIN) { value = await refreshGoogleCalendarCredential(value); await prisma.connectorCredential.update({ where: { sourceId: source.id }, data: encryptConnectorPayload(value, c) }); } return value; }
function dateTime(value?: { date?: string; dateTime?: string; timeZone?: string }) { if (!value?.dateTime) return null; const date = new Date(value.dateTime); return Number.isNaN(date.getTime()) ? null : date; }
async function applyEvents(source: Source, calendar: Prisma.ExternalCalendarGetPayload<Record<string, never>>, items: GoogleCalendarEvent[]) { let upserted = 0, deleted = 0; for (const event of items) { if (!event.id) throw new GoogleCalendarAdapterError("PROVIDER_RESPONSE_INVALID"); if (event.status === "cancelled") { await prisma.externalCalendarEvent.updateMany({ where: { externalCalendarRecordId: calendar.id, externalEventId: event.id }, data: { isDeleted: true, status: "cancelled", sourceEtag: event.etag, syncedAt: new Date() } }); deleted++; continue; }
    await prisma.externalCalendarEvent.upsert({ where: { externalCalendarRecordId_externalEventId: { externalCalendarRecordId: calendar.id, externalEventId: event.id } }, create: { companyId: source.companyId, connectorSourceId: source.id, externalCalendarRecordId: calendar.id, externalEventId: event.id, sourceEtag: event.etag, status: event.status, summary: event.summary?.slice(0, 1000), description: event.description?.slice(0, 10000), location: event.location?.slice(0, 1000), startAt: dateTime(event.start), endAt: dateTime(event.end), startDate: event.start?.date, endDate: event.end?.date, timeZone: event.start?.timeZone, organiserEmail: event.organizer?.email?.toLowerCase(), attendeeEmails: [...new Set((event.attendees ?? []).flatMap(a => a.email ? [a.email.toLowerCase()] : []))].slice(0, 500), transparency: event.transparency, visibility: event.visibility, recurringEventId: event.recurringEventId, htmlLink: event.htmlLink, syncedAt: new Date() }, update: { sourceEtag: event.etag, status: event.status, summary: event.summary?.slice(0, 1000), description: event.description?.slice(0, 10000), location: event.location?.slice(0, 1000), startAt: dateTime(event.start), endAt: dateTime(event.end), startDate: event.start?.date, endDate: event.end?.date, timeZone: event.start?.timeZone, organiserEmail: event.organizer?.email?.toLowerCase(), attendeeEmails: [...new Set((event.attendees ?? []).flatMap(a => a.email ? [a.email.toLowerCase()] : []))].slice(0, 500), transparency: event.transparency, visibility: event.visibility, recurringEventId: event.recurringEventId, htmlLink: event.htmlLink, isDeleted: false, syncedAt: new Date() } }); upserted++; } return { upserted, deleted }; }

export async function syncGoogleCalendar(user: AuthedUser, sourceId: string): Promise<ServiceResult<unknown>> {
  const source = await prisma.connectorSource.findFirst({ where: { id: sourceId, companyId: user.companyId, connectorKey: "google_calendar", isActive: true }, include: { credential: true } }); if (!source) return fail(404, "CONNECTOR_SOURCE_NOT_FOUND"); if (!source.isEnabled) return fail(409, "CONNECTOR_NOT_ENABLED"); if (!source.credential) return fail(409, "CONNECTOR_AUTHORIZATION_REQUIRED");
  try { const auth = await usable(source); let calendarFallback = false; let list;
    try { list = await listGoogleCalendars(auth.accessToken, { syncToken: source.syncCursor ?? undefined, pageToken: source.syncPageToken ?? undefined }); } catch (e) { if (!(e instanceof GoogleCalendarAdapterError) || e.code !== "SYNC_TOKEN_EXPIRED") throw e; calendarFallback = true; await prisma.connectorSource.update({ where: { id: source.id }, data: { syncCursor: null, syncPageToken: null } }); list = await listGoogleCalendars(auth.accessToken, {}); }
    for (const item of list.items ?? []) { if (!item.id) throw new GoogleCalendarAdapterError("PROVIDER_RESPONSE_INVALID"); await prisma.externalCalendar.upsert({ where: { companyId_connectorSourceId_externalCalendarId: { companyId: source.companyId, connectorSourceId: source.id, externalCalendarId: item.id } }, create: { companyId: source.companyId, connectorSourceId: source.id, externalCalendarId: item.id, summary: item.summary ?? item.id, description: item.description, timeZone: item.timeZone, accessRole: item.accessRole, isPrimary: item.primary ?? false, isDeleted: item.deleted ?? false }, update: { summary: item.summary ?? item.id, description: item.description, timeZone: item.timeZone, accessRole: item.accessRole, isPrimary: item.primary ?? false, isDeleted: item.deleted ?? false } }); }
    const now = new Date(); await prisma.connectorSource.update({ where: { id: source.id }, data: { syncPageToken: list.nextPageToken ?? null, ...(list.nextSyncToken ? { syncCursor: list.nextSyncToken, lastFullSyncAt: source.syncCursor ? source.lastFullSyncAt : now } : {}), lastSyncAt: now, lastSyncStatus: "success", lastErrorCode: null } });
    const calendars = await prisma.externalCalendar.findMany({ where: { companyId: source.companyId, connectorSourceId: source.id, isDeleted: false }, orderBy: [{ isPrimary: "desc" }, { summary: "asc" }] }); let eventsUpserted = 0, eventsDeleted = 0, eventFallbacks = 0, eventPagesRemaining = 0;
    for (let calendar of calendars) { let response; try { response = await listGoogleCalendarEvents(auth.accessToken, calendar.externalCalendarId, { syncToken: calendar.eventSyncToken ?? undefined, pageToken: calendar.eventPageToken ?? undefined }); } catch (e) { if (!(e instanceof GoogleCalendarAdapterError) || e.code !== "SYNC_TOKEN_EXPIRED") throw e; eventFallbacks++; await prisma.$transaction([prisma.externalCalendarEvent.deleteMany({ where: { externalCalendarRecordId: calendar.id } }), prisma.externalCalendar.update({ where: { id: calendar.id }, data: { eventSyncToken: null, eventPageToken: null } })]); response = await listGoogleCalendarEvents(auth.accessToken, calendar.externalCalendarId, {}); }
      const counts = await applyEvents(source, calendar, response.items ?? []); eventsUpserted += counts.upserted; eventsDeleted += counts.deleted; if (response.nextPageToken) eventPagesRemaining++; await prisma.externalCalendar.update({ where: { id: calendar.id }, data: { eventPageToken: response.nextPageToken ?? null, ...(response.nextSyncToken ? { eventSyncToken: response.nextSyncToken } : {}), lastEventSyncAt: now } }); }
    const result = { sourceId, mode: source.syncCursor ? "incremental" : "full", calendarFallback, calendarsSeen: list.items?.length ?? 0, eventsUpserted, eventsDeleted, eventFallbacks, hasMore: Boolean(list.nextPageToken) || eventPagesRemaining > 0, syncedAt: now };
    await recordAudit({ companyId: user.companyId, userId: user.id, actionName: SYNC_GOOGLE_CALENDAR_ACTION.actionName, inputPayload: { sourceId }, dataAfter: result, riskLevel: 2, result: "success" }); return ok(200, result);
  } catch (error) { const result = providerError(error); const code = result.ok ? "CONNECTOR_INTERNAL_ERROR" : result.error; await prisma.connectorSource.update({ where: { id: source.id }, data: { lastSyncAt: new Date(), lastSyncStatus: "error", lastErrorCode: code } }); return result; }
}

export async function listExternalCalendarEvents(user: AuthedUser, sourceId: string, raw: unknown): Promise<ServiceResult<unknown>> { const parsed = eventQuerySchema.safeParse(raw); if (!parsed.success) return fail(400, "VALIDATION_FAILED", parsed.error.message); const source = await prisma.connectorSource.findFirst({ where: { id: sourceId, companyId: user.companyId, connectorKey: "google_calendar" } }); if (!source) return fail(404, "CONNECTOR_SOURCE_NOT_FOUND"); const where: Prisma.ExternalCalendarEventWhereInput = { companyId: user.companyId, connectorSourceId: sourceId, ...(parsed.data.include_deleted === "true" ? {} : { isDeleted: false }) }; const [items, total] = await prisma.$transaction([prisma.externalCalendarEvent.findMany({ where, include: { externalCalendar: { select: { summary: true, timeZone: true, isPrimary: true } } }, orderBy: [{ startAt: "asc" }, { startDate: "asc" }], skip: parsed.data.offset, take: parsed.data.limit }), prisma.externalCalendarEvent.count({ where })]); return ok(200, { items, total, offset: parsed.data.offset, limit: parsed.data.limit }); }

export async function disconnectGoogleCalendarSource(user: AuthedUser, sourceId: string, raw: unknown): Promise<ServiceResult<unknown>> { const parsed = disconnectSchema.safeParse(raw); if (!parsed.success) return fail(400, "VALIDATION_FAILED"); const source = await prisma.connectorSource.findFirst({ where: { id: sourceId, companyId: user.companyId, connectorKey: "google_calendar", isActive: true }, include: { credential: true } }); if (!source) return fail(404, "CONNECTOR_SOURCE_NOT_FOUND"); const preview = { sourceId, provider: "google_calendar", willRevokeGoogleProjectGrant: Boolean(source.credential), willKeepStagedEvents: true }; if (!parsed.data.confirmed) return fail(409, "CONFIRMATION_REQUIRED", undefined, { preview }); await prisma.connectorSource.update({ where: { id: source.id }, data: { isEnabled: false, connectionStatus: "disconnecting" } }); try { if (source.credential) await revokeGoogleCalendarCredential(decryptConnectorPayload<StoredGoogleCalendarCredential>(source.credential, context(source.companyId, source.id)).refreshToken); const disconnectedAt = new Date(); await prisma.$transaction([prisma.connectorCredential.deleteMany({ where: { sourceId } }), prisma.connectorOAuthState.deleteMany({ where: { sourceId } }), prisma.connectorSource.update({ where: { id: sourceId }, data: { isEnabled: false, connectionStatus: "disconnected", syncCursor: null, syncPageToken: null, lastFullSyncAt: null, lastErrorCode: null } })]); const result = { sourceId, provider: "google_calendar", providerGrantRevoked: Boolean(source.credential), disconnectedAt }; await recordAudit({ companyId: user.companyId, userId: user.id, actionName: DISCONNECT_GOOGLE_CALENDAR_SOURCE_ACTION.actionName, inputPayload: { sourceId, confirmed: true }, dataAfter: result, riskLevel: 3, confirmationRequired: true, confirmed: true, result: "success" }); return ok(200, result); } catch (error) { const result = providerError(error); await prisma.connectorSource.update({ where: { id: sourceId }, data: { isEnabled: false, connectionStatus: "disconnect_failed", lastErrorCode: result.ok ? "CONNECTOR_INTERNAL_ERROR" : result.error } }); return result; } }
