import { z } from "zod";
import { prisma } from "../db.js";
import { recordAudit } from "../lib/audit.js";
import type { AuthedUser } from "../middleware/auth.js";
import { fail, ok, type ServiceResult } from "./result.js";
import { RECORD_INVOICE_PAYMENT_ACTION } from "../lib/actionContracts.js";

const item = z.object({ description: z.string().min(1), quantity: z.number().positive().default(1), unit_price: z.number().nonnegative() });
const createSchema = z.object({ client_id: z.string().uuid(), invoice_number: z.string().min(1), title: z.string().min(1), issue_date: z.string().datetime().optional(), due_date: z.string().datetime().optional(), notes: z.string().optional(), items: z.array(item).min(1) });
const paymentSchema = z.object({ amount: z.number().positive(), paid_at: z.string().datetime(), method: z.string().optional(), reference: z.string().optional(), confirmed:z.boolean().optional() });
const statusSchema = z.object({ invoice_status: z.enum(["draft", "issued", "void"]) });
const include = { client: { select: { id: true, displayName: true } }, items: { orderBy: { sortOrder: "asc" as const } }, payments: { orderBy: { paidAt: "asc" as const } } };
function totals<T extends { items: { quantity:number;unitPrice:number }[];payments:{amount:number}[];dueDate:Date|null;invoiceStatus:string }>(x:T){const total=x.items.reduce((s,i)=>s+i.quantity*i.unitPrice,0),paid=x.payments.reduce((s,p)=>s+p.amount,0),balance=Math.max(0,total-paid);return {...x,totals:{total,paid,balance},isOverdue:x.invoiceStatus==="issued"&&balance>0&&!!x.dueDate&&x.dueDate<new Date()};}
export async function listInvoices(u:AuthedUser){return (await prisma.invoice.findMany({where:{companyId:u.companyId},include,orderBy:{createdAt:"desc"}})).map(totals);}
export async function getInvoice(u:AuthedUser,id:string){const x=await prisma.invoice.findFirst({where:{id,companyId:u.companyId},include});return x?totals(x):null;}
export async function createInvoice(u:AuthedUser,raw:unknown):Promise<ServiceResult<unknown>>{const p=createSchema.safeParse(raw);if(!p.success)return fail(400,"VALIDATION_FAILED",p.error.message);const d=p.data;if(!await prisma.client.findFirst({where:{id:d.client_id,companyId:u.companyId}}))return fail(404,"CLIENT_NOT_FOUND");if(await prisma.invoice.findUnique({where:{companyId_invoiceNumber:{companyId:u.companyId,invoiceNumber:d.invoice_number}}}))return fail(409,"INVOICE_NUMBER_EXISTS");const x=await prisma.invoice.create({data:{companyId:u.companyId,clientId:d.client_id,invoiceNumber:d.invoice_number,title:d.title,issueDate:d.issue_date?new Date(d.issue_date):undefined,dueDate:d.due_date?new Date(d.due_date):undefined,notes:d.notes,createdBy:u.id,items:{create:d.items.map((i,n)=>({description:i.description,quantity:i.quantity,unitPrice:i.unit_price,sortOrder:n}))}},include});await recordAudit({companyId:u.companyId,userId:u.id,actionName:"create_invoice",inputPayload:d,dataAfter:x,riskLevel:2,confirmationRequired:false,result:"success"});return ok(201,totals(x));}
export async function changeInvoiceStatus(u:AuthedUser,id:string,raw:unknown):Promise<ServiceResult<unknown>>{const p=statusSchema.safeParse(raw);if(!p.success)return fail(400,"VALIDATION_FAILED");const old=await prisma.invoice.findFirst({where:{id,companyId:u.companyId}});if(!old)return fail(404,"INVOICE_NOT_FOUND");const x=await prisma.invoice.update({where:{id},data:{invoiceStatus:p.data.invoice_status,issueDate:p.data.invoice_status==="issued"?(old.issueDate??new Date()):old.issueDate},include});await recordAudit({companyId:u.companyId,userId:u.id,actionName:"change_invoice_status",inputPayload:{id,...p.data},dataBefore:old,dataAfter:x,riskLevel:2,confirmationRequired:false,result:"success"});return ok(200,totals(x));}
export async function addPayment(u:AuthedUser,id:string,raw:unknown):Promise<ServiceResult<unknown>>{const p=paymentSchema.safeParse(raw);if(!p.success)return fail(400,"VALIDATION_FAILED",p.error.message);const inv=await getInvoice(u,id);if(!inv)return fail(404,"INVOICE_NOT_FOUND");if(inv.invoiceStatus==="void")return fail(409,"INVOICE_VOID");if(p.data.amount>inv.totals.balance)return fail(409,"PAYMENT_EXCEEDS_BALANCE");const input={invoiceId:id,amount:p.data.amount,paid_at:p.data.paid_at,method:p.data.method,reference:p.data.reference};const preview={invoiceId:id,invoiceNumber:inv.invoiceNumber,client:inv.client.displayName,amount:p.data.amount,balanceBefore:inv.totals.balance,balanceAfter:inv.totals.balance-p.data.amount,willMarkPaid:inv.totals.balance===p.data.amount};if(!p.data.confirmed){await recordAudit({companyId:u.companyId,userId:u.id,actionName:RECORD_INVOICE_PAYMENT_ACTION.actionName,inputPayload:input,dataBefore:{balance:inv.totals.balance},riskLevel:RECORD_INVOICE_PAYMENT_ACTION.riskLevel,confirmationRequired:true,result:"rejected",errorMessage:"CONFIRMATION_REQUIRED"});return fail(409,"CONFIRMATION_REQUIRED","Review the payment preview and confirm.",{preview})}await prisma.payment.create({data:{invoiceId:id,amount:p.data.amount,paidAt:new Date(p.data.paid_at),method:p.data.method,reference:p.data.reference}});const updated=await getInvoice(u,id);if(updated&&updated.totals.balance===0)await prisma.invoice.update({where:{id},data:{invoiceStatus:"paid"}});await recordAudit({companyId:u.companyId,userId:u.id,actionName:RECORD_INVOICE_PAYMENT_ACTION.actionName,inputPayload:input,dataBefore:{balance:inv.totals.balance},dataAfter:{balance:preview.balanceAfter},riskLevel:RECORD_INVOICE_PAYMENT_ACTION.riskLevel,confirmationRequired:true,confirmed:true,result:"success"});return ok(201,await getInvoice(u,id));}
