export const GOOGLE_DRIVE_FILE_SCOPE = "https://www.googleapis.com/auth/drive.file";
const AUTH = "https://accounts.google.com/o/oauth2/v2/auth";
const TOKEN = "https://oauth2.googleapis.com/token";
const REVOKE = "https://oauth2.googleapis.com/revoke";
const FILE_FIELDS = "id,name,mimeType,webViewLink,thumbnailLink,parents,size,imageMediaMetadata(width,height),createdTime,modifiedTime,trashed";
export interface StoredGoogleDriveCredential { accessToken: string; refreshToken: string; scopes: string[]; tokenType: string; expiresAt: string }
interface TokenResponse { access_token?: string; refresh_token?: string; expires_in?: number; scope?: string; token_type?: string }
export interface GoogleDriveFile { id?: string; name?: string; mimeType?: string; webViewLink?: string; thumbnailLink?: string; parents?: string[]; size?: string; imageMediaMetadata?: { width?: number; height?: number }; createdTime?: string; modifiedTime?: string; trashed?: boolean }
export class GoogleDriveAdapterError extends Error { constructor(public readonly code: "CONNECTOR_CONFIGURATION_MISSING" | "OAUTH_PROVIDER_REJECTED" | "CONNECTOR_AUTHORIZATION_REQUIRED" | "SCOPE_DENIED" | "RATE_LIMITED" | "PROVIDER_UNAVAILABLE" | "FILE_NOT_FOUND" | "NOT_AN_IMAGE" | "PROVIDER_RESPONSE_INVALID", message = code) { super(message); } }
function config() { const clientId = process.env.GOOGLE_DRIVE_OAUTH_CLIENT_ID?.trim(), clientSecret = process.env.GOOGLE_DRIVE_OAUTH_CLIENT_SECRET?.trim(), redirectUri = process.env.GOOGLE_DRIVE_OAUTH_REDIRECT_URI?.trim(); if (!clientId || !clientSecret || !redirectUri) throw new GoogleDriveAdapterError("CONNECTOR_CONFIGURATION_MISSING"); try { const u = new URL(redirectUri); if (!["http:", "https:"].includes(u.protocol) || (u.protocol === "http:" && !["localhost", "127.0.0.1", "::1"].includes(u.hostname))) throw new Error(); } catch { throw new GoogleDriveAdapterError("CONNECTOR_CONFIGURATION_MISSING"); } return { clientId, clientSecret, redirectUri }; }
const scopes = (value?: string) => [...new Set((value ?? "").split(/\s+/).filter(Boolean))];
function credential(r: TokenResponse, old?: string): StoredGoogleDriveCredential { const granted = scopes(r.scope); if (!r.access_token || !r.expires_in || r.expires_in <= 0) throw new GoogleDriveAdapterError("OAUTH_PROVIDER_REJECTED"); if (granted.length !== 1 || granted[0] !== GOOGLE_DRIVE_FILE_SCOPE) throw new GoogleDriveAdapterError("SCOPE_DENIED"); const refreshToken = r.refresh_token ?? old; if (!refreshToken) throw new GoogleDriveAdapterError("CONNECTOR_AUTHORIZATION_REQUIRED"); return { accessToken: r.access_token, refreshToken, scopes: granted, tokenType: r.token_type ?? "Bearer", expiresAt: new Date(Date.now() + r.expires_in * 1000).toISOString() }; }
async function token(body: URLSearchParams) { let r: Response; try { r = await fetch(TOKEN, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body }); } catch { throw new GoogleDriveAdapterError("PROVIDER_UNAVAILABLE"); } if (!r.ok) { if (r.status === 429) throw new GoogleDriveAdapterError("RATE_LIMITED"); if (r.status >= 500) throw new GoogleDriveAdapterError("PROVIDER_UNAVAILABLE"); throw new GoogleDriveAdapterError("OAUTH_PROVIDER_REJECTED"); } try { return await r.json() as TokenResponse; } catch { throw new GoogleDriveAdapterError("PROVIDER_RESPONSE_INVALID"); } }
export function buildGoogleDriveAuthorizationUrl(state: string) { const c = config(), u = new URL(AUTH); u.search = new URLSearchParams({ client_id: c.clientId, redirect_uri: c.redirectUri, response_type: "code", scope: GOOGLE_DRIVE_FILE_SCOPE, access_type: "offline", prompt: "consent", state }).toString(); return u.toString(); }
export async function exchangeGoogleDriveAuthorizationCode(code: string, old?: string) { const c = config(); return credential(await token(new URLSearchParams({ client_id: c.clientId, client_secret: c.clientSecret, code, grant_type: "authorization_code", redirect_uri: c.redirectUri })), old); }
export async function refreshGoogleDriveCredential(value: StoredGoogleDriveCredential) { const c = config(), r = await token(new URLSearchParams({ client_id: c.clientId, client_secret: c.clientSecret, refresh_token: value.refreshToken, grant_type: "refresh_token" })); if (!r.scope) r.scope = value.scopes.join(" "); return credential(r, value.refreshToken); }
export async function getGoogleDriveImage(accessToken: string, fileId: string) { const u = new URL(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(fileId)}`); u.searchParams.set("fields", FILE_FIELDS); u.searchParams.set("supportsAllDrives", "true"); let r: Response; try { r = await fetch(u, { headers: { Authorization: `Bearer ${accessToken}` } }); } catch { throw new GoogleDriveAdapterError("PROVIDER_UNAVAILABLE"); } if (!r.ok) { if (r.status === 404) throw new GoogleDriveAdapterError("FILE_NOT_FOUND"); if (r.status === 401) throw new GoogleDriveAdapterError("CONNECTOR_AUTHORIZATION_REQUIRED"); if (r.status === 403) throw new GoogleDriveAdapterError("SCOPE_DENIED"); if (r.status === 429) throw new GoogleDriveAdapterError("RATE_LIMITED"); throw new GoogleDriveAdapterError("PROVIDER_UNAVAILABLE"); } let file: GoogleDriveFile; try { file = await r.json() as GoogleDriveFile; } catch { throw new GoogleDriveAdapterError("PROVIDER_RESPONSE_INVALID"); } if (!file.id || !file.name || !file.mimeType) throw new GoogleDriveAdapterError("PROVIDER_RESPONSE_INVALID"); if (!file.mimeType.startsWith("image/") || file.trashed) throw new GoogleDriveAdapterError("NOT_AN_IMAGE"); return file; }
export async function revokeGoogleDriveCredential(refreshToken: string) { let r: Response; try { r = await fetch(REVOKE, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ token: refreshToken }) }); } catch { throw new GoogleDriveAdapterError("PROVIDER_UNAVAILABLE"); } if (r.ok) return; if (r.status === 429) throw new GoogleDriveAdapterError("RATE_LIMITED"); if (r.status >= 500) throw new GoogleDriveAdapterError("PROVIDER_UNAVAILABLE"); throw new GoogleDriveAdapterError("OAUTH_PROVIDER_REJECTED"); }
